include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    avoid_print: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_relative_lib_imports: true

analyzer:
  exclude:
    - out/**
    - packages/hg_native/pigeons/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    missing_required_param: error
    missing_return: error
